import { pool } from '../../../config/db';

export class UserAssignmentsRepository {
    async getUsers(tenantId: string) {
        const result = await pool.query(
            `SELECT 
                e.id as employee_id, e.name, e.email, e.department, e.position,
                u.id, u.role, u.is_active, u.last_login, u.role_id,
                u.temp_password, u.is_password_temp,
                r.name as role_name
             FROM employees e
             LEFT JOIN users u ON e.email = u.email AND (e.tenant_id = u.tenant_id OR u.tenant_id IS NULL)
             LEFT JOIN roles r ON r.id = u.role_id
             WHERE (e.tenant_id = $1 OR e.tenant_id IS NULL) AND e.deleted_at IS NULL
             ORDER BY u.id DESC NULLS LAST, e.name ASC`,
            [tenantId]
        );
        return result.rows;
    }

    async getUsersFallback() {
        const fallback = await pool.query('SELECT id, name, email, role FROM users LIMIT 100');
        return fallback.rows;
    }

    async checkEmailExists(email: string) {
        const existing = await pool.query('SELECT id FROM users WHERE email=$1', [email]);
        return existing.rows.length > 0;
    }

    async getRoleIdByName(role: string, tenantId: string) {
        const roleResult = await pool.query('SELECT id FROM roles WHERE tenant_id=$1 AND name=$2', [tenantId, role]);
        return roleResult.rows[0]?.id || null;
    }

    async createUser(tenantId: string, data: any, hashedPassword: string, finalPassword: string | null, isAutoGenerated: boolean, resolvedRoleId: number | null) {
        const result = await pool.query(
            `INSERT INTO users (name, email, password, role, tenant_id, role_id, is_active, temp_password, is_password_temp)
             VALUES ($1,$2,$3,$4,$5,$6,true,$7,$8) RETURNING id, name, email, role, is_active, temp_password`,
            [data.name, data.email, hashedPassword, data.role || 'employee', tenantId, resolvedRoleId, isAutoGenerated ? finalPassword : null, isAutoGenerated]
        );
        return result.rows[0];
    }

    async getUser(id: string, tenantId: string) {
        const userResult = await pool.query(
            'SELECT u.id, u.name, u.email, u.role, u.temp_password, u.is_password_temp FROM users u WHERE u.id=$1 AND u.tenant_id=$2',
            [id, tenantId]
        );
        return userResult.rows[0];
    }

    async updatePassword(id: string, tenantId: string, hashed: string, tempPass: string | null, isTemp: boolean) {
        const result = await pool.query(
            `UPDATE users SET password=$1, temp_password=$2, is_password_temp=$3 
             WHERE id=$4 AND tenant_id=$5 RETURNING email, name`,
            [hashed, tempPass, isTemp, id, tenantId]
        );
        return result.rows[0];
    }

    async updateUserRole(id: string, tenantId: string, role: string | null, roleId: number | null) {
        await pool.query(
            `UPDATE users SET role=COALESCE($1,role), role_id=$2 WHERE id=$3 AND tenant_id=$4`,
            [role, roleId, id, tenantId]
        );
    }

    async updateUserStatus(id: string, tenantId: string, is_active: boolean) {
        await pool.query(`UPDATE users SET is_active=$1 WHERE id=$2 AND tenant_id=$3`, [is_active, id, tenantId]);
    }

    async deleteUser(id: string, tenantId: string) {
        await pool.query(`UPDATE users SET deleted_at=NOW(), is_active=false WHERE id=$1 AND tenant_id=$2`, [id, tenantId]);
    }
}
