import bcrypt from 'bcryptjs';
import { UserAssignmentsRepository } from './user-assignments.repository';
import { AppError } from '../../../core/errors/AppError';
import { AuthzActor, assertMayAssignRole, assertMayManageUser, resolveRoleForNewAccount } from '../../../core/security/authzState';

// The role a new account gets when the request names none (a default, not an authorization rule).
const BASELINE_ROLE_NAME = 'employee';
import { NotificationService } from '../../../services/notificationService';
import { sendEmail, buildWelcomeEmail, buildRoleAssignmentEmail } from '../../../services/emailService';
import { getOrganizationName } from '../../workspace/workspace.service';
import { BRAND } from '../../../config/brand';

export class UserAssignmentsService {
    private repo: UserAssignmentsRepository;

    constructor() {
        this.repo = new UserAssignmentsRepository();
    }

    async getUsers(tenantId: string) {
        try {
            return { data: await this.repo.getUsers(tenantId) };
        } catch (err: any) {
            console.error('FETCH_USERS_ERROR:', err.message);
            return { data: await this.repo.getUsersFallback(tenantId), warning: 'Limited data mode' };
        }
    }

    async createUser(actor: AuthzActor, data: any) {
        const tenantId = actor.tenantId;
        const { name, email, password, role, role_id, send_welcome_email = false } = data;

        if (!name || !email) throw AppError.badRequest('Name and email are required.');
        if (await this.repo.checkEmailExists(email)) throw AppError.badRequest('A user with this email already exists.');

        const isAutoGenerated = !password;
        const finalPassword = password || Math.random().toString(36).slice(-10).toUpperCase();
        const hashedPassword = await bcrypt.hash(finalPassword, 10);

        // The role is resolved and authorized BEFORE anything is written; the client's role string is only a lookup key.
        const grantedRole = await resolveRoleForNewAccount(actor, { roleId: role_id, roleName: role }, BASELINE_ROLE_NAME);

        const newUser = await this.repo.createUser(tenantId, { ...data, role: grantedRole.name }, hashedPassword, finalPassword, isAutoGenerated, grantedRole.id);

        await NotificationService.onAccountCreated(tenantId, newUser.id, name);

        if (send_welcome_email) {
            const loginUrl = process.env.APP_URL || 'http://localhost:5173';
            const orgName = await getOrganizationName(tenantId);
            await sendEmail({
                to: email,
                subject: `Welcome to ${orgName || BRAND.productName} — your account is ready`,
                html: buildWelcomeEmail({ name, email, tempPassword: password, role: grantedRole.name, loginUrl, orgName: orgName || undefined }),
            });
        }
        return newUser;
    }

    async sendWelcome(id: string, actor: AuthzActor, temp_password?: string) {
        const tenantId = actor.tenantId;
        const user = await this.repo.getUser(id, tenantId);
        if (!user) throw AppError.notFound('User');
        if (temp_password) await assertMayManageUser(actor, Number(id)); // it sets that account's password

        const tempPass = temp_password || Math.random().toString(36).slice(-10).toUpperCase();
        if (temp_password) {
            const hashed = await bcrypt.hash(tempPass, 10);
            await this.repo.updatePassword(id, tenantId, hashed, tempPass, true);
        }

        const loginUrl = process.env.APP_URL || 'http://localhost:5173';
        const orgName = await getOrganizationName(tenantId);
        const sent = await sendEmail({
            to: user.email,
            subject: `Welcome to ${orgName || BRAND.productName} — your account is ready`,
            html: buildWelcomeEmail({ name: user.name, email: user.email, tempPassword: tempPass, role: user.role, loginUrl, orgName: orgName || undefined }),
        });

        return { sent, message: sent ? 'Welcome email sent.' : 'No SMTP config. Email not sent.' };
    }

    async resetPassword(id: string, actor: AuthzActor) {
        const tenantId = actor.tenantId;
        await assertMayManageUser(actor, Number(id));
        const tempPass = Math.random().toString(36).slice(-10).toUpperCase();
        const hashed = await bcrypt.hash(tempPass, 10);
        const user = await this.repo.updatePassword(id, tenantId, hashed, tempPass, true);
        if (!user) throw AppError.notFound('User');
        return tempPass;
    }

    async updatePassword(id: string, actor: AuthzActor, password: string) {
        const tenantId = actor.tenantId;
        if (!password) throw AppError.badRequest('Password is required.');
        await assertMayManageUser(actor, Number(id));
        const hashedPassword = await bcrypt.hash(password, 10);
        const user = await this.repo.updatePassword(id, tenantId, hashedPassword, password, true);
        if (!user) throw AppError.notFound('User');
    }

    async updateUserRole(id: string, actor: AuthzActor, role?: string, role_id?: number, notify_user = false) {
        const tenantId = actor.tenantId;
        // Needs roles:assign, a role this tenant can see that the actor covers, a target the actor covers, and not oneself.
        const granted = await assertMayAssignRole(actor, Number(id), { roleId: role_id, roleName: role });
        role = granted.name;
        await this.repo.updateUserRole(id, tenantId, granted.name, granted.id);

        if (notify_user) {
            const user = await this.repo.getUser(id, tenantId);
            if (user) {
                const loginUrl = process.env.APP_URL || 'http://localhost:5173';
                const orgName = await getOrganizationName(tenantId);
                await sendEmail({
                    to: user.email,
                    subject: 'Your role has been updated',
                    html: buildRoleAssignmentEmail({ name: user.name, email: user.email, role: role || '', loginUrl, orgName: orgName || undefined }),
                });
            }
        }
        await NotificationService.onRoleUpdated(tenantId, parseInt(id), role || 'Updated Role');
    }

    async updateUserStatus(id: string, actor: AuthzActor, is_active: boolean) {
        if (Number(id) === actor.userId) throw AppError.forbidden('You cannot change your own status.');
        await assertMayManageUser(actor, Number(id));
        await this.repo.updateUserStatus(id, actor.tenantId, Boolean(is_active));
    }

    async deleteUser(id: string, actor: AuthzActor) {
        if (parseInt(id) === actor.userId) throw AppError.badRequest('You cannot delete your own account.');
        await assertMayManageUser(actor, Number(id));
        await this.repo.deleteUser(id, actor.tenantId);
    }
}
