import bcrypt from 'bcryptjs';
import { UserAssignmentsRepository } from './user-assignments.repository';
import { AppError } from '../../../core/errors/AppError';
import { NotificationService } from '../../../services/notificationService';
import { sendEmail, buildWelcomeEmail, buildRoleAssignmentEmail } from '../../../services/emailService';

export class UserAssignmentsService {
    private repo: UserAssignmentsRepository;

    constructor() {
        this.repo = new UserAssignmentsRepository();
    }

    async getUsers(tenantId: string) {
        try {
            return { data: await this.repo.getUsers(tenantId) };
        } catch (err: any) {
            console.error('FETCH_USERS_ERROR:', err.message);
            return { data: await this.repo.getUsersFallback(), warning: 'Limited data mode' };
        }
    }

    async createUser(tenantId: string, data: any) {
        const { name, email, password, role = 'employee', role_id, send_welcome_email = false } = data;
        
        if (!name || !email) throw AppError.badRequest('Name and email are required.');
        if (await this.repo.checkEmailExists(email)) throw AppError.badRequest('A user with this email already exists.');

        const isAutoGenerated = !password;
        const finalPassword = password || Math.random().toString(36).slice(-10).toUpperCase();
        const hashedPassword = await bcrypt.hash(finalPassword, 10);

        let resolvedRoleId = role_id;
        if (!resolvedRoleId) {
            resolvedRoleId = await this.repo.getRoleIdByName(role, tenantId);
        }

        const newUser = await this.repo.createUser(tenantId, data, hashedPassword, finalPassword, isAutoGenerated, resolvedRoleId);

        await NotificationService.onAccountCreated(tenantId, newUser.id, name);

        if (send_welcome_email) {
            const loginUrl = process.env.APP_URL || 'http://localhost:5173';
            await sendEmail({
                to: email,
                subject: '🎉 Welcome — Your account is ready',
                html: buildWelcomeEmail({ name, email, tempPassword: password, role, loginUrl }),
            });
        }
        return newUser;
    }

    async sendWelcome(id: string, tenantId: string, temp_password?: string) {
        const user = await this.repo.getUser(id, tenantId);
        if (!user) throw AppError.notFound('User');

        const tempPass = temp_password || Math.random().toString(36).slice(-10).toUpperCase();
        if (temp_password) {
            const hashed = await bcrypt.hash(tempPass, 10);
            await this.repo.updatePassword(id, tenantId, hashed, tempPass, true);
        }

        const loginUrl = process.env.APP_URL || 'http://localhost:5173';
        const sent = await sendEmail({
            to: user.email,
            subject: '🎉 Welcome — Your AURA account is ready',
            html: buildWelcomeEmail({ name: user.name, email: user.email, tempPassword: tempPass, role: user.role, loginUrl }),
        });

        return { sent, message: sent ? 'Welcome email sent.' : 'No SMTP config. Email not sent.' };
    }

    async resetPassword(id: string, tenantId: string) {
        const tempPass = Math.random().toString(36).slice(-10).toUpperCase();
        const hashed = await bcrypt.hash(tempPass, 10);
        const user = await this.repo.updatePassword(id, tenantId, hashed, tempPass, true);
        if (!user) throw AppError.notFound('User');
        return tempPass;
    }

    async getTempPassword(id: string, tenantId: string) {
        const user = await this.repo.getUser(id, tenantId);
        if (!user) throw AppError.notFound('User');
        return { temp_password: user.temp_password, is_password_temp: user.is_password_temp };
    }

    async updatePassword(id: string, tenantId: string, password: string) {
        if (!password) throw AppError.badRequest('Password is required.');
        const hashedPassword = await bcrypt.hash(password, 10);
        const user = await this.repo.updatePassword(id, tenantId, hashedPassword, password, true);
        if (!user) throw AppError.notFound('User');
    }

    async updateUserRole(id: string, tenantId: string, role?: string, role_id?: number, notify_user = false) {
        let resolvedRoleId = role_id;
        if (!resolvedRoleId && role) {
            resolvedRoleId = await this.repo.getRoleIdByName(role, tenantId);
        }
        await this.repo.updateUserRole(id, tenantId, role || null, resolvedRoleId || null);

        if (notify_user) {
            const user = await this.repo.getUser(id, tenantId);
            if (user) {
                const loginUrl = process.env.APP_URL || 'http://localhost:5173';
                await sendEmail({
                    to: user.email,
                    subject: '🔑 Your role has been updated',
                    html: buildRoleAssignmentEmail({ name: user.name, email: user.email, role: role || '', loginUrl }),
                });
            }
        }
        await NotificationService.onRoleUpdated(tenantId, parseInt(id), role || 'Updated Role');
    }

    async updateUserStatus(id: string, tenantId: string, is_active: boolean) {
        await this.repo.updateUserStatus(id, tenantId, Boolean(is_active));
    }

    async deleteUser(id: string, tenantId: string, currentUserId: number) {
        if (parseInt(id) === currentUserId) throw AppError.badRequest('You cannot delete your own account.');
        await this.repo.deleteUser(id, tenantId);
    }
}
